### PR TITLE
PROD-4228 Adopt TaxJar beta extension (transaction-sync branch)

### PR DESCRIPTION
**Pull request by igor-tereshchenko**
* removed order save listener
* removed order/creditmemo multiple saves
* removed product loads
* added 2 separate tables to track orders/creditmemos sync times

### CODE REVIEW

**Review by halk — APPROVED** [review]

**Review by halk — APPROVED** [review]

**Comment by halk** [comment]
this is still not merged and is used via dev-PROD-4228

**Comment by igor-tereshchenko** [comment]
Transaction sync branch isn't merged to taxjar master either, we have our optimisations sit on top of it.
We can merge it, but it will be more difficult to apply new updates from the origin.

**Comment by halk** [comment]
do you still want to keep this PR open?

**Comment by igor-tereshchenko** [comment]
PR can be closed, but leave this branch unmerged, that makes applying
upstream changes easier

**Pull request closed without merging**
